# Generated by Django 2.0.4 on 2018-04-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180419_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='numbersupp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
